site_name: Data Engineering University
repo_url: https://github.com/pavs23/data-engineering-university
repo_name: data-engineering-university
theme:
  name: material
  palette:
    primary: green
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - instant
    - search.highlight